Repository PredictiveHire/phapp-schedule-link, pull requests merged in 2024-06, with the labels that each got.

#6 chore: update page title and favicon
  index.html
  public/static/android-chrome-144x144.png
  public/static/apple-touch-icon.png
  public/static/favicon.ico
  public/static/favicon.png
  public/static/favicon.svg
  public/static/site.webmanifest
Labels: chore

#3 feat: [LI-181] implement ui for candidate select interview time
  package.json
  pnpm-lock.yaml
  src/assets/images/ww-logo.svg
  src/components/__test__/RBErrorBoundary.test.tsx
  src/config/theme.json
  src/pages/__tests__/ErrorPage.test.tsx
  src/pages/__tests__/NotFoundPage.test.tsx
  src/pages/schedule-interview/ScheduleInterviewPage.tsx
  src/pages/schedule-interview/__test__/ScheduleInterviewPage.test.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/MobileCandidateSelectInterviewTime.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/__test__/MobileCandidateSelectInterviewTime.test.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewInfo/MobileInterviewInfo.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewInfo/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewTimeSlotBooking/MobileInterviewTimeSlotBooking.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewTimeSlotBooking/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewTimeSlotBooking/styles.module.css
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/__test__/MobileInterviewInfo.test.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/__test__/MobileInterviewTimeSlotBooking.test.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/constants/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/constants/interviewInfo.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/hooks/useInterviewBooking.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/hooks/useInterviewDate.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/hooks/useTimeSlots.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/styles.module.css
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/type/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/type/interviewTimeSlot.ts
  src/router/index.tsx
  src/utils/__test__/apolloErrorCheck.test.ts
  src/utils/__test__/dateTime.test.ts
  src/utils/__test__/getApiPath.test.ts
  src/utils/__test__/regionMapping.test.ts
  src/utils/dateTime.ts
  src/utils/regionMapping.ts
  tailwind.config.ts
Labels: feat

#5 feat: [LI-187] invalid link message
  index.html
  jest/unit-incremental.config.ts
  src/pages/InvalidLinkPage/InvalidLinkPage.tsx
  src/pages/InvalidLinkPage/__tests__/InvalidLinkPage.test.tsx
  src/pages/InvalidLinkPage/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/MobileCandidateSelectInterviewTime.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/hooks/useInterviewDate.ts
  src/router/index.tsx
  tailwind.config.ts
Labels: feat

#4 feat: [LI-52] implement ui for mobile confirmation page
  package.json
  pnpm-lock.yaml
  src/pages/schedule-interview/ScheduleInterviewPage.tsx
  src/pages/schedule-interview/components/MobileCandidateConfirmation/MobileCandidateConfirmation.tsx
  src/pages/schedule-interview/components/MobileCandidateConfirmation/MobileCandidateConfirmationInfo.tsx
  src/pages/schedule-interview/components/MobileCandidateConfirmation/__test__/MobileCandidateConfirmation.test.tsx
  src/pages/schedule-interview/components/MobileCandidateConfirmation/__test__/MobileCandidateConfirmationInfo.test.tsx
  src/pages/schedule-interview/components/MobileCandidateConfirmation/hooks/useCandidateConfirmation.ts
  src/pages/schedule-interview/components/MobileCandidateConfirmation/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/hooks/useTimeSlots.ts
  src/utils/__test__/dateTime.test.ts
  src/utils/dateTime.ts
Labels: feat

#7 feat: [LI-268] desktop confirmation page
  src/pages/schedule-interview/ScheduleInterviewPage.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/CandidateConfirmation.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/CandidateConfirmationInfo.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/__test__/CandidateConfirmation.test.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/__test__/CandidateConfirmationInfo.test.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/hooks/useCandidateConfirmation.ts
  src/pages/schedule-interview/components/CandidateConfirmation/index.ts
  src/pages/schedule-interview/components/MobileCandidateConfirmation/MobileCandidateConfirmation.tsx
  src/pages/schedule-interview/components/MobileCandidateConfirmation/MobileCandidateConfirmationInfo.tsx
  src/pages/schedule-interview/components/MobileCandidateConfirmation/index.ts
  src/utils/dateTime.ts
  tailwind.config.ts
Labels: feat, refactor

#8 feat: [LI-50] implement desktop ui for candidate select interview time
  src/pages/schedule-interview/ScheduleInterviewPage.tsx
  src/pages/schedule-interview/__test__/ScheduleInterviewPage.test.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/CandidateConfirmation.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/__test__/CandidateConfirmation.test.tsx
  src/pages/schedule-interview/components/CandidateConfirmation/hooks/useCandidateConfirmation.ts
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/DesktopCandidateSelectInterviewTime.tsx
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/__test__/DesktopCandidateSelectInterviewTime.test.tsx
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/components/DesktopInterviewTimeSlotBooking/DesktopInterviewTimeSlotBooking.tsx
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/components/DesktopInterviewTimeSlotBooking/index.ts
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/components/DesktopInterviewTimeSlotBooking/styles.module.css
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/components/__test__/DesktopInterviewTimeSlotBooking.test.tsx
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/hooks/useDesktopInterviewDate.ts
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/hooks/useSelectTimeSlot.ts
  src/pages/schedule-interview/components/DesktopCandidateSelectInterviewTime/index.ts
  src/pages/schedule-interview/components/InterviewInfo/InterviewInfo.tsx
  src/pages/schedule-interview/components/InterviewInfo/InterviewInfoItem.tsx
  src/pages/schedule-interview/components/InterviewInfo/__test__/InterviewInfo.test.tsx
  src/pages/schedule-interview/components/InterviewInfo/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/MobileCandidateSelectInterviewTime.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/__test__/MobileCandidateSelectInterviewTime.test.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewInfo/MobileInterviewInfo.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewInfo/index.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewTimeSlotBooking/MobileInterviewTimeSlotBooking.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/MobileInterviewTimeSlotBooking/styles.module.css
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/__test__/MobileInterviewInfo.test.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/components/__test__/MobileInterviewTimeSlotBooking.test.tsx
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/hooks/useInterviewBooking.ts
  src/pages/schedule-interview/components/MobileCandidateSelectInterviewTime/type/interviewTimeSlot.ts
  src/pages/schedule-interview/components/SelectTimeSlotsRadioGroup/SelectTimeSlotsRadioGroup.tsx
  src/pages/schedule-interview/components/SelectTimeSlotsRadioGroup/__test__/SelectTimeSlotsRadioGroup.test.tsx
  src/pages/schedule-interview/constants/index.ts
  src/pages/schedule-interview/constants/interviewInfo.ts
  src/pages/schedule-interview/hooks/__test__/useCalendarHeader.test.ts
  src/pages/schedule-interview/hooks/useCalendarHeader.ts
  src/pages/schedule-interview/hooks/useTimeSlots.ts
  src/pages/schedule-interview/type/index.ts
  src/pages/schedule-interview/type/interviewTimeSlot.ts
  src/utils/__test__/dateTime.test.ts
  src/utils/dateTime.ts
Labels: feat
